// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/usecase/user/create.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/usecase/user/create.go -destination=internal/application/usecase/user/mock/create.go
//

// Package mock_userusecase is a generated GoMock package.
package mock_userusecase

import (
	context "context"
	reflect "reflect"

	userusecase "github.com/EduCoelhoTs/base-hex-arq-api/internal/application/usecase/user"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateUserUseCase is a mock of CreateUserUseCase interface.
type MockCreateUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUserUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateUserUseCaseMockRecorder is the mock recorder for MockCreateUserUseCase.
type MockCreateUserUseCaseMockRecorder struct {
	mock *MockCreateUserUseCase
}

// NewMockCreateUserUseCase creates a new mock instance.
func NewMockCreateUserUseCase(ctrl *gomock.Controller) *MockCreateUserUseCase {
	mock := &MockCreateUserUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUserUseCase) EXPECT() *MockCreateUserUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateUserUseCase) Execute(ctx context.Context, input userusecase.CreateUserInput) (userusecase.CreateUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(userusecase.CreateUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateUserUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateUserUseCase)(nil).Execute), ctx, input)
}
